language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - "make vendor"
  - "export PHP_INI=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini"
  - "if [ \"$TRAVIS_PHP_VERSION\" == \"5.4\" ]; then echo \"extension=apc.so\" >> ${PHP_INI}; fi"
  - "if [ \"$TRAVIS_PHP_VERSION\" == \"5.5\" ]; then printf \"\\n\" | pecl install apcu-beta; fi"
  - "if [ \"$TRAVIS_PHP_VERSION\" == \"5.6\" ]; then printf \"\\n\" | pecl install apcu-beta; fi"
  - "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then echo \"apc.enable_cli = 1\" >> ${PHP_INI}; fi"

script: make

cache:
  directories:
    - vendor

sudo: false
